{"Uri": "/pointat", "Name": "PointAt", "Nickname": "PtAt", "Description": "Get point along curve", "Category": "Hops", "Subcategory": "Hops Python", "Inputs": [{"Name": "Curve", "Nickname": "C", "Description": "Curve to evaluate", "ParamType": "Curve", "ResultType": "Rhino.Geometry.Curve", "AtLeast": 1, "AtMost": 1}, {"Name": "t", "Nickname": "t", "Description": "Parameter on Curve to evaluate", "ParamType": "Number", "ResultType": "System.Double", "AtLeast": 1, "AtMost": 1, "Default": 0.0}], "Outputs": [{"Name": "P", "Nickname": "P", "Description": "Point on curve at t", "ParamType": "Point", "ResultType": "Rhino.Geometry.Point3d", "AtLeast": 1, "AtMost": 1}]}